Add styling to feedback form and page
Glow-Carrots-App/glow-web pull request #21
Opened 2022-08-11 20:19 UTC by RobbyGardner

Create feedback form for feedback subpage

<img width="342" alt="Screen Shot 2022-08-11 at 1 16 35 PM" src="https://user-images.githubusercontent.com/93552075/184234824-922cb77b-9184-4ce2-8d01-b89658bb375a.png">
.

2022-08-11 20:25 UTC, gochoa1088 requested changes

2022-08-11 20:25 UTC, gochoa1088 commented on components/FeedbackForm/styles.module.css
> +/* .subjectField {
clean up comments

2022-08-11 20:25 UTC, gochoa1088 commented on pages/settings/feedback/index.js
> +      <FeedbackForm></FeedbackForm>
can use the shorthand of component injection

2022-08-11 20:25 UTC, gochoa1088 commented on components/FeedbackForm/index.js
> +      <label>Subject</label>
for forms, labels usually wrap the element we are trying to label

https://reactjs.org/docs/forms.html

2022-08-11 21:06 UTC, gochoa1088 approved these changes
nice job linking labels to their input fields

2022-08-11 21:06 UTC, merged

2022-08-12 01:13 UTC, joelcolucci commented on components/FeedbackForm/index.js
> +    <form className={styles.container}>
Nice work! Good looking form HTML.